version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: captcha-db-dev
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: captcha-backend-dev
    restart: unless-stopped
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-postgres}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/usr/local/tomcat/logs
    networks:
      - internal
    depends_on:
      - db

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: captcha-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - internal
    depends_on:
      - backend

networks:
  internal:
    driver: bridge

volumes:
  postgres_data:
