version: '3.8'

services:
  backend:
    image: melihemreguler/captcha-backend:latest
    container_name: captcha-backend
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=captcha.melihemre.dev
      - VIRTUAL_PATH=/api
      - LETSENCRYPT_HOST=captcha.melihemre.dev
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./logs:/usr/local/tomcat/logs
    networks:
      - web
      - internal
    depends_on:
      - frontend

  frontend:
    image: melihemreguler/captcha-frontend:latest
    container_name: captcha-frontend
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=captcha.melihemre.dev
      - VIRTUAL_PATH=/
      - LETSENCRYPT_HOST=captcha.melihemre.dev
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - web
      - internal

networks:
  web:
    name: web
    external: true
  internal:
    driver: bridge
